export const FALLBACK_SERVICES = [
  {
    _id: '1',
    id: '1',
    name: 'AC Repair & Diagnostics',
    nameAr: 'صيانة وفحص المكيفات',
    description: 'Expert diagnostics and repair for all split, window, and central AC systems. We fix cooling faults, gas leaks, electrical issues, and unusual noises.',
    descriptionAr: 'تشخيص وإصلاح احترافي لجميع أنواع مكيفات الاسبليت والشباك والمركزي. صيانة ضعف التبريد وتسريب الفريون والأعطال الكهربائية.',
    basePrice: 150,
    estimatedDuration: '1-2 hours',
    category: 'ac',
    isPopular: true,
    warrantyDays: 30,
  },
  {
    _id: '2',
    id: '2',
    name: 'AC Installation & Dismantling',
    nameAr: 'تركيب وفك مكيفات سبليت وشباك',
    description: 'Professional installation for new or relocated split and window air conditioners with vacuum testing and leak-free copper piping.',
    descriptionAr: 'تركيب احترافي لمكيفات الاسبليت والشباك الجديدة أو المنقولة مع فحص التفريغ وتمديد النحاس بدون تسريبات.',
    basePrice: 200,
    estimatedDuration: '2-3 hours',
    category: 'ac',
    isPopular: true,
    warrantyDays: 30,
  },
  {
    _id: '3',
    id: '3',
    name: 'AC Deep Cleaning & Sanitization',
    nameAr: 'تنظيف وغسيل المكيفات',
    description: 'High-pressure jet wash and chemical sanitization of evaporator coils, blower fan, filters, and drain lines for maximum airflow and cooling.',
    descriptionAr: 'غسيل عميق بأجهزة ضغط الماء العالي ومواد التعقيم لملفات التبريد والمروحة والفلاتر ومجرى التصريف لزيادة كفاءة التبريد ونقاء الهواء.',
    basePrice: 100,
    estimatedDuration: '1-2 hours',
    category: 'ac',
    isPopular: true,
    warrantyDays: 30,
  },
  {
    _id: '4',
    id: '4',
    name: 'Refrigerator & Freezer Repair',
    nameAr: 'إصلاح الثلاجات والفريزر',
    description: 'Comprehensive repair for all refrigerator and freezer brands. Thermostat replacement, compressor repair, defrost timer fixes, and gas charging.',
    descriptionAr: 'إصلاح شامل لجميع ماركات الثلاجات والفريزر. تغيير الثرموستات، صيانة الكمبروسر، معالجة تراكم الثلج وشحن الفريون الأصلي.',
    basePrice: 150,
    estimatedDuration: '1-2 hours',
    category: 'refrigerator',
    isPopular: true,
    warrantyDays: 30,
  },
  {
    _id: '5',
    id: '5',
    name: 'Washing Machine Repair',
    nameAr: 'إصلاح وصيانة الغسالات',
    description: 'Expert repair for front-load and top-load washers: motor issues, water drainage, noisy bearings, and electronic PCB boards.',
    descriptionAr: 'إصلاح جميع أنواع الغسالات الأوتوماتيك والعادية: مشاكل دوران الحوض، طرد المياه، اهتزاز التجفيف ولوحات التحكم.',
    basePrice: 140,
    estimatedDuration: '1-2 hours',
    category: 'washing-machine',
    isPopular: true,
    warrantyDays: 30,
  },
  {
    _id: '6',
    id: '6',
    name: 'AC Gas Refill (Freon R410A / R22)',
    nameAr: 'تعبئة غاز فريون أصلي',
    description: 'Starting from 180 SAR (prices vary depending on gas type R410A/R22 & quantity needed). Pressure test, leak detection, complete evacuation, and 100% genuine refrigerant refill.',
    descriptionAr: 'يبدأ من 180 ريال (تختلف القيمة حسب نوع الغاز R410A / R22 وكمية الشحن المطلوبة). شحن فريون أصلي مع كشف وتصليح مكان التسريب وفحص الضغوط.',
    basePrice: 180,
    estimatedDuration: '1 hour',
    category: 'ac',
    isPopular: true,
    warrantyDays: 30,
  },
  {
    _id: '7',
    id: '7',
    name: 'Cooking Stove & Oven Repair',
    nameAr: 'صيانة الأفران والبوتاجازات',
    description: 'Burner cleaning, ignition fixes, thermostat replacement, and gas safety checks.',
    descriptionAr: 'صيانة شعلات الغاز وتغيير الحساسات وضبط درجات حرارة الأفران.',
    basePrice: 160,
    estimatedDuration: '1-2 hours',
    category: 'stove',
    isPopular: false,
    warrantyDays: 30,
  },
  {
    _id: '8',
    id: '8',
    name: 'Electrical Wiring Fix',
    nameAr: 'صيانة التمديدات والأعطال الكهربائية',
    description: 'Distribution board breaker repairs, short circuit troubleshooting, appliance power sockets, and load balancing.',
    descriptionAr: 'فحص وإصلاح القواطع الكهربائية، كشف الماس الكهربائي، وتأمين دوائر التكييف والأجهزة المنزلية.',
    basePrice: 120,
    estimatedDuration: '1-2 hours',
    category: 'general',
    isPopular: false,
    warrantyDays: 30,
  },
  {
    _id: '9',
    id: '9',
    name: 'Central AC Service',
    nameAr: 'صيانة التكييف المركزي والدكت',
    description: 'Commercial and residential central HVAC chiller maintenance, duct cleaning, thermostat automation, and airflow balancing.',
    descriptionAr: 'صيانة دورية للمباني والفلل وأنظمة التكييف المركزي والمخفي والدكت مع فحص ضواغط التبريد وفلاتر الهواء.',
    basePrice: 350,
    estimatedDuration: '2-4 hours',
    category: 'ac',
    isPopular: true,
    warrantyDays: 30,
  },
  {
    _id: 'pkg_villa',
    id: 'pkg_villa',
    name: 'Annual Villa Care - Full Home Maintenance',
    nameAr: 'عقد رعاية سنوية للفلل والمنازل',
    description: '4 seasonal AC maintenance visits, VIP priority 24/7 hotline dispatch, and 20% off all spare parts.',
    descriptionAr: '٤ زيارات فحص دوري للمكيفات مع صيانة طوارئ ذات أولوية قصوى وخصم ٢٠٪ على قطع الغيار.',
    basePrice: 1200,
    estimatedDuration: 'Annual Contract',
    category: 'general',
    isPopular: true,
    warrantyDays: 365,
  },
];
